"""empty message

Revision ID: 10a396e22467
Revises: 
Create Date: 2019-12-02 19:38:22.653835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10a396e22467'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('path', sa.String(length=64), nullable=True, comment='用于查询出子分类的文章'))
    op.drop_column('user_info', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('password', mysql.VARCHAR(length=255), nullable=True, comment='密码'))
    op.drop_column('category', 'path')
    # ### end Alembic commands ###
