"""modify post column markdown_html_code

Revision ID: 1fcc0de9c5b7
Revises: fd2d1ec4dfa0
Create Date: 2019-08-21 20:46:30.849818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fcc0de9c5b7'
down_revision = 'fd2d1ec4dfa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('markdown_html_code', sa.Text(), nullable=True, comment='Post内容'))
    op.drop_column('posts', 'html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('html', mysql.TEXT(), nullable=True, comment='Post内容'))
    op.drop_column('posts', 'markdown_html_code')
    # ### end Alembic commands ###
