"""分类添加is_directory

Revision ID: 2a07c67b5360
Revises: e3a34353983d
Create Date: 2019-12-08 19:04:33.674812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a07c67b5360'
down_revision = 'e3a34353983d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_directory', sa.Integer(), nullable=True, comment='判断是否是父级，只要有下一级就是父级'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_directory')
    # ### end Alembic commands ###
