"""add category

Revision ID: 31ee1d89b0bc
Revises: ccaf5fbf7cdb
Create Date: 2019-08-11 12:27:21.788822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ee1d89b0bc'
down_revision = 'ccaf5fbf7cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True, comment='分类名称'),
    sa.Column('title', sa.String(length=64), nullable=True, comment='url标识'),
    sa.Column('keywords', sa.String(length=128), nullable=True, comment='分类关键词'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='列表排序'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='分类描述'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
