"""add category create_time

Revision ID: 497f0f94391a
Revises: 4f80885b744f
Create Date: 2019-08-11 20:21:35.652735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '497f0f94391a'
down_revision = '4f80885b744f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('create_time', sa.Integer(), nullable=True, comment='创建时间'))
    op.alter_column('category', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='父分类ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='父分类ID',
               existing_nullable=True)
    op.drop_column('category', 'create_time')
    # ### end Alembic commands ###
