"""add category pid

Revision ID: 4f80885b744f
Revises: 31ee1d89b0bc
Create Date: 2019-08-11 20:07:44.196267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f80885b744f'
down_revision = '31ee1d89b0bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('pid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'pid')
    # ### end Alembic commands ###
