"""update comment

Revision ID: 53c09c71d8b8
Revises: 6250c5526eb6
Create Date: 2019-06-30 21:47:41.434734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53c09c71d8b8'
down_revision = '6250c5526eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_base', 'email',
               existing_type=mysql.VARCHAR(length=64),
               comment='邮箱',
               existing_nullable=True)
    op.alter_column('user_base', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码',
               existing_nullable=True)
    op.alter_column('user_base', 'username',
               existing_type=mysql.VARCHAR(length=64),
               comment='用户名',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_base', 'username',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='用户名',
               existing_nullable=True)
    op.alter_column('user_base', 'password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='密码',
               existing_nullable=True)
    op.alter_column('user_base', 'email',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=True)
    # ### end Alembic commands ###
