"""update comment

Revision ID: 6a5f1ad5afa8
Revises: 53c09c71d8b8
Create Date: 2019-06-30 21:53:48.478420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a5f1ad5afa8'
down_revision = '53c09c71d8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_base', 'city',
               existing_type=mysql.VARCHAR(length=16),
               comment='城市',
               existing_nullable=True)
    op.alter_column('user_base', 'company',
               existing_type=mysql.VARCHAR(length=32),
               comment='公司',
               existing_nullable=True)
    op.alter_column('user_base', 'description',
               existing_type=mysql.VARCHAR(length=255),
               comment='个人简介',
               existing_nullable=True)
    op.alter_column('user_base', 'gender',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='性别',
               existing_nullable=True)
    op.alter_column('user_base', 'name',
               existing_type=mysql.VARCHAR(length=64),
               comment='真实姓名',
               existing_nullable=True)
    op.alter_column('user_base', 'nickname',
               existing_type=mysql.VARCHAR(length=64),
               comment='用户昵称',
               existing_nullable=True)
    op.alter_column('user_base', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               comment='手机',
               existing_nullable=True)
    op.alter_column('user_base', 'signature',
               existing_type=mysql.VARCHAR(length=255),
               comment='个人签名',
               existing_nullable=True)
    op.alter_column('user_base', 'title',
               existing_type=mysql.VARCHAR(length=32),
               comment='头衔，职位',
               existing_nullable=True)
    op.alter_column('user_base', 'website',
               existing_type=mysql.VARCHAR(length=128),
               comment='个人网站，博客',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_base', 'website',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='个人网站，博客',
               existing_nullable=True)
    op.alter_column('user_base', 'title',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='头衔，职位',
               existing_nullable=True)
    op.alter_column('user_base', 'signature',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='个人签名',
               existing_nullable=True)
    op.alter_column('user_base', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               comment=None,
               existing_comment='手机',
               existing_nullable=True)
    op.alter_column('user_base', 'nickname',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='用户昵称',
               existing_nullable=True)
    op.alter_column('user_base', 'name',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='真实姓名',
               existing_nullable=True)
    op.alter_column('user_base', 'gender',
               existing_type=mysql.SMALLINT(display_width=6),
               comment=None,
               existing_comment='性别',
               existing_nullable=True)
    op.alter_column('user_base', 'description',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='个人简介',
               existing_nullable=True)
    op.alter_column('user_base', 'company',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='公司',
               existing_nullable=True)
    op.alter_column('user_base', 'city',
               existing_type=mysql.VARCHAR(length=16),
               comment=None,
               existing_comment='城市',
               existing_nullable=True)
    # ### end Alembic commands ###
