"""update modeules import methods

Revision ID: 818e13a11120
Revises: ad310b3c9a6d
Create Date: 2019-08-28 21:47:38.765171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '818e13a11120'
down_revision = 'ad310b3c9a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission')
    op.drop_table('permission_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_group',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='组ID'),
    sa.Column('name', mysql.VARCHAR(length=16), nullable=True, comment='组名'),
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('permission',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='权限ID'),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='权限组'),
    sa.Column('name', mysql.VARCHAR(length=16), nullable=True, comment='权限名称'),
    sa.Column('code', mysql.VARCHAR(length=32), nullable=True, comment='权限码'),
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['group_id'], ['permission_group.id'], name='permission_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
