"""add Language model

Revision ID: 84d18889b025
Revises: d0c159db56f6
Create Date: 2019-08-24 21:58:19.458851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d18889b025'
down_revision = 'd0c159db56f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True, comment='语言名称'),
    sa.Column('code', sa.String(length=12), nullable=True, comment='国家简码'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态'),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language')
    # ### end Alembic commands ###
