"""评论功能数据库

Revision ID: a793a8c79171
Revises: 2a07c67b5360
Create Date: 2019-12-26 22:58:13.612068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a793a8c79171'
down_revision = '2a07c67b5360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True, comment='评论人'),
    sa.Column('to_uid', sa.Integer(), nullable=True, comment='评论哪条评论'),
    sa.Column('body', sa.Text(), nullable=True, comment='评论内容'),
    sa.Column('body_html', sa.Text(), nullable=True, comment='转化后的评论内容'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='评论审核'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
