"""add permission and group

Revision ID: ad310b3c9a6d
Revises: 84d18889b025
Create Date: 2019-08-28 21:44:05.132038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad310b3c9a6d'
down_revision = '84d18889b025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_group',
    sa.Column('id', sa.Integer(), nullable=False, comment='组ID'),
    sa.Column('name', sa.String(length=16), nullable=True, comment='组名'),
    sa.Column('create_time', sa.Integer(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.Integer(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False, comment='权限ID'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='权限组'),
    sa.Column('name', sa.String(length=16), nullable=True, comment='权限名称'),
    sa.Column('code', sa.String(length=32), nullable=True, comment='权限码'),
    sa.Column('create_time', sa.Integer(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.Integer(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['group_id'], ['permission_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('language', 'name',
               existing_type=mysql.VARCHAR(length=64),
               comment='语言名称',
               existing_nullable=True)
    op.create_unique_constraint(None, 'language', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'language', type_='unique')
    op.alter_column('language', 'name',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='语言名称',
               existing_nullable=True)
    op.drop_table('permission')
    op.drop_table('permission_group')
    # ### end Alembic commands ###
