"""update permissionGroup NAME 

Revision ID: b8c9c341bf6e
Revises: 706ac2204a4a
Create Date: 2019-08-29 21:31:32.064609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c9c341bf6e'
down_revision = '706ac2204a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'permission_group', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission_group', type_='unique')
    # ### end Alembic commands ###
