"""update userbase

Revision ID: ccaf5fbf7cdb
Revises: 6a5f1ad5afa8
Create Date: 2019-07-02 23:23:25.426495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccaf5fbf7cdb'
down_revision = '6a5f1ad5afa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_base', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('user_base', sa.Column('uuid', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'user_base', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_base', type_='unique')
    op.drop_column('user_base', 'uuid')
    op.drop_column('user_base', 'avatar_url')
    # ### end Alembic commands ###
