"""修改post表

Revision ID: d0e024212dd5
Revises: ffd684f28006
Create Date: 2019-08-19 20:48:19.571853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0e024212dd5'
down_revision = 'ffd684f28006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_html', sa.Text(), nullable=True, comment='Post内容'))
    op.add_column('posts', sa.Column('content_markdown', sa.Text(), nullable=True, comment='存储markdown文本'))
    op.add_column('posts', sa.Column('references', sa.Text(), nullable=True, comment='参考文献'))
    op.add_column('posts', sa.Column('subtitle', sa.String(length=64), nullable=True, comment='副标题'))
    op.drop_column('posts', 'content')
    op.drop_column('posts', 'markdown_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('markdown_content', mysql.TEXT(), nullable=True, comment='存储markdown文本'))
    op.add_column('posts', sa.Column('content', mysql.TEXT(), nullable=True, comment='Post内容'))
    op.drop_column('posts', 'subtitle')
    op.drop_column('posts', 'references')
    op.drop_column('posts', 'content_markdown')
    op.drop_column('posts', 'content_html')
    # ### end Alembic commands ###
