"""modify Roles column

Revision ID: d4e71ec31bc4
Revises: 54f4141f4e50
Create Date: 2019-09-08 11:28:06.885584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e71ec31bc4'
down_revision = '54f4141f4e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('create_time', sa.Integer(), nullable=True, comment='创建时间'))
    op.add_column('roles', sa.Column('update_time', sa.Integer(), nullable=True, comment='更新时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'update_time')
    op.drop_column('roles', 'create_time')
    # ### end Alembic commands ###
