"""分类添加level字段

Revision ID: e3a34353983d
Revises: 10a396e22467
Create Date: 2019-12-08 17:35:52.548988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a34353983d'
down_revision = '10a396e22467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('level', sa.Integer(), nullable=True, comment='分类级别'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'level')
    # ### end Alembic commands ###
