"""post 表和用户、分类表关联

Revision ID: f3010831c4ec
Revises: 497f0f94391a
Create Date: 2019-08-18 19:29:53.886198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3010831c4ec'
down_revision = '497f0f94391a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID，该文章属于那个用户'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='该文章属于哪个分类'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='文章标题'),
    sa.Column('title', sa.String(length=64), nullable=True, comment='文章url'),
    sa.Column('keywords', sa.String(length=128), nullable=True, comment='文章关键词'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='文章描述'),
    sa.Column('markdown_content', sa.Text(), nullable=True, comment='存储markdown文本'),
    sa.Column('content', sa.Text(), nullable=True, comment='Post内容'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态'),
    sa.Column('marked', sa.SmallInteger(), nullable=True, comment='推荐内容'),
    sa.Column('clicks', sa.Integer(), nullable=True, comment='点击阅读数'),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.Integer(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
