"""update modeules import methods

Revision ID: f566170f9db6
Revises: 818e13a11120
Create Date: 2019-08-28 21:50:45.360073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f566170f9db6'
down_revision = '818e13a11120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_group',
    sa.Column('id', sa.Integer(), nullable=False, comment='组ID'),
    sa.Column('name', sa.String(length=16), nullable=True, comment='组名'),
    sa.Column('create_time', sa.Integer(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.Integer(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False, comment='权限ID'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='权限组'),
    sa.Column('name', sa.String(length=16), nullable=True, comment='权限名称'),
    sa.Column('code', sa.String(length=32), nullable=True, comment='权限码'),
    sa.Column('create_time', sa.Integer(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.Integer(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['group_id'], ['permission_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission')
    op.drop_table('permission_group')
    # ### end Alembic commands ###
