"""modify post column name

Revision ID: fd2d1ec4dfa0
Revises: d0e024212dd5
Create Date: 2019-08-20 20:52:03.717642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd2d1ec4dfa0'
down_revision = 'd0e024212dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('html', sa.Text(), nullable=True, comment='Post内容'))
    op.add_column('posts', sa.Column('markdown', sa.Text(), nullable=True, comment='存储markdown文本'))
    op.drop_column('posts', 'content_markdown')
    op.drop_column('posts', 'content_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_html', mysql.TEXT(), nullable=True, comment='Post内容'))
    op.add_column('posts', sa.Column('content_markdown', mysql.TEXT(), nullable=True, comment='存储markdown文本'))
    op.drop_column('posts', 'markdown')
    op.drop_column('posts', 'html')
    # ### end Alembic commands ###
