"""修改post表

Revision ID: ffd684f28006
Revises: f3010831c4ec
Create Date: 2019-08-18 19:41:02.627940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffd684f28006'
down_revision = 'f3010831c4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID，该文章属于那个用户'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='该文章属于哪个分类'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='文章标题'),
    sa.Column('title', sa.String(length=64), nullable=True, comment='文章url'),
    sa.Column('keywords', sa.String(length=128), nullable=True, comment='文章关键词'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='文章描述'),
    sa.Column('markdown_content', sa.Text(), nullable=True, comment='存储markdown文本'),
    sa.Column('content', sa.Text(), nullable=True, comment='Post内容'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态'),
    sa.Column('marked', sa.SmallInteger(), nullable=True, comment='推荐内容'),
    sa.Column('clicks', sa.Integer(), nullable=True, comment='点击阅读数'),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.Integer(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.drop_index('title', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='用户ID，该文章属于那个用户'),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='该文章属于哪个分类'),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True, comment='文章标题'),
    sa.Column('title', mysql.VARCHAR(length=64), nullable=True, comment='文章url'),
    sa.Column('keywords', mysql.VARCHAR(length=128), nullable=True, comment='文章关键词'),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True, comment='文章描述'),
    sa.Column('markdown_content', mysql.TEXT(), nullable=True, comment='存储markdown文本'),
    sa.Column('content', mysql.TEXT(), nullable=True, comment='Post内容'),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='状态'),
    sa.Column('marked', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='推荐内容'),
    sa.Column('clicks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='点击阅读数'),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='post_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user_base.id'], name='post_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('title', 'post', ['title'], unique=True)
    op.drop_table('posts')
    # ### end Alembic commands ###
